brightwind/transform/transform.py
brightwind/utils/utils.py

function to adjust a wind speed with a new slope and offset.
I have written lots of tests in a jupyter notebook. These will need to be properly implemented in the test area.

iss12_add adjust_slope_offset function

---

brightwind/analyse/analyse.py

I have fixed the bug you introduced. You sent the coverage function 'data' which is already monthly data instead of sending it the input data.
I changed the behaviour that if return_coverage=True then it would send back the data. This might change once we add coverage to the plot.
For the coverage function to work I had to remove the changing of wdspds to a list. I do not know why you do this? Will this break something else?
I have also fixed the argument in the doc string and modified the examples.

Fixed #1 - fixed bug introduced by issue #1 and modified doc string

---

brightwind/analyse/analyse.py
brightwind/analyse/correlation.py
brightwind/analyse/plot.py
brightwind/load/load.py
brightwind/transform/transform.py

Consistency in wind speed and direction names across the library as in issue #4. Also change dataframe to DataFrame.

Standardise wind speed and wind direction to wspd and wdir

---

brightwind/analyse/analyse.py
brightwind/tests/test_analyse.py
brightwind/tests/test_transform.py
brightwind/transform/transform.py

@stephenholleran For your perusal.

Iss22 coverage average data by period docs test

---

brightwind/analyse/analyse.py
brightwind/analyse/correlation.py

Merging the new feature branch to the master.

Iss42 add direction synthesis to speed sort

---

brightwind/load/__init__.py
brightwind/load/load.py

Add a function to load a Windographer formatted data file exported from the software.
@Inder95 can you take a look at this and merge if happy?

Iss #53 load windographer txt

---

brightwind/load/load.py

Changed the behaviour to match Windographer and Python selection in general.

iss #10 change behaviour of selecting to not include the end date

---

brightwind/analyse/analyse.py
brightwind/analyse/plot.py
brightwind/tests/test_analyse.py

Issue #44 
Please review and once you are done I will merge the changes. Let me resolve the conflicts, its easy when you do it in the browser itself.

Iss44 sector ratio by sector plot warning

---

brightwind/analyse/plot.py
brightwind/tests/test_plot.py
brightwind/utils/utils.py

Let me know if you are happy with suggestions implemented from iss #56

Iss56 plot timeseries enhancements

---

brightwind/analyse/analyse.py
brightwind/analyse/plot.py
brightwind/tests/test_analyse.py
requirements.txt

Add tests and update docstring for twelve_by_24(). Iss #57

---

brightwind/export/export.py

Fix function to create tab files which import correctly into windfarmer. Change header line in tab files to include time and date of file creation, brightwind library version used and the mean wind speed. Create new private function, _calc_mean_wind_speed_of_freq_tab, to support export_tab_file and add to export.py.

Iss #38 #65 export tab file

---

brightwind/analyse/analyse.py
brightwind/analyse/plot.py
brightwind/tests/test_transform.py
brightwind/transform/transform.py

Add fixes to remove future deprecation warnings

Iss81 monthly means

---

brightwind/analyse/analyse.py

Break function  'wspd_ratio_by_dir' out from the class 'SectorRatio' and remove function SectorRatio.calc

Iss88 sector ratio

---

brightwind/tests/test_analyse.py
brightwind/tests/test_export.py
brightwind/tests/test_transform.py

Add test_export_to_csv
Update tests test_sector_ratio_by_sector, export_tab_file and test_offset_timestamp. All tests in the library now complete successfully.

 test functions update

---

brightwind/__init__.py
brightwind/analyse/analyse.py
brightwind/analyse/correlation.py
brightwind/analyse/plot.py
brightwind/transform/transform.py
brightwind/utils/utils.py

Issue #95 to remove access to private functions when you hit tab in Jupyter notebook

iss #95 remove access to private functions.

---

brightwind/analyse/analyse.py

Update tests for wspd_ratio_by_dir_sector and twelve_by_24 to work with recent changes to code

Iss91 tests

---

docs/source/tutorials/how_to_load_data.ipynb

New section includes r prefix and bw.datasets.. exaplanations

iss #126 restructure load tutorial with new filepath section

---

brightwind/analyse/shear.py

Set names of outputted series of alpha / roughness.

iss #184 set names of shear/roughness series

---

brightwind/analyse/analyse.py

Fix bugs in _get_dis_matrix_by_dir_sector()

Iss99 dist matrix by dir sector

---

brightwind/analyse/plot.py

fixed legend issue. IEC class elements are now shown in the legend.

iss #233 fix legend issue

---

brightwind/export/export.py

rephrased the tab file header from ' Mean wind speed for tab file is:" to "Mean wind speed derived from this tab file is:"

iss #235 rephrased tab file header

---

brightwind/analyse/plot.py
brightwind/analyse/shear.py

fixed issue when datasets is shorter than 1 year

Iss232 shear time of day

---

brightwind/export/export.py
setup.py

updated export_tab_file function to output the version of the brightwind module in the header.

iss #200 fix version output in export_tab_file

---

brightwind/analyse/analyse.py
brightwind/tests/test_analyse.py

If a Data Frame is sent it will calculate avg wind directions for each row.

Iss #254 add capability to send a DataFrame

---

brightwind/analyse/correlation.py
tests/test_correlation.py

Add the capability to provide different aggregation methods such as 'sum' to handle solar irradiation or energy data.
Applied to:
- OrdinaryLeastSquares
- OrthogonalLeastSquares
- MultipleLinearRegression

Iss #245 correl agg sum

---

brightwind/analyse/correlation.py

Iss294 fix speed sort sector missing

---

CHANGELOG.md
brightwind/analyse/analyse.py
brightwind/transform/transform.py
tests/test_analyse.py
tests/test_transform.py

Iss297 add argument average data by period

---

tests/test_export.py

fixed error generated when running this test...generated temp folder inside \tests

iss #314 fix reference path

---

brightwind/export/export.py

iss #324 replace is with ==

---

brightwind/transform/transform.py
tests/test_transform.py

bug fixed and added test for 1D and 15D timesteps

[_get_data_resolution] bug on deriving data resolution for daily timesteps

---

CHANGELOG.md
brightwind/analyse/analyse.py
brightwind/analyse/plot.py
brightwind/analyse/shear.py
tests/test_analyse.py
tests/test_plot.py

Added subplotting functionality.

Iss309 sector ratio subplot

---

CHANGELOG.md
brightwind/analyse/analyse.py
brightwind/transform/transform.py
brightwind/utils/utils.py
tests/test_analyse.py

Method implemented as reported in #334

[Iss334] freq table seasonal adjusted

---

brightwind/analyse/analyse.py

- added ValueError when aggregation method is  set to 'count' for `_get_dist_matrix_by_dir_sector_seasonal_adjusted`
- added ValueError when freq_as_percentage=False and seasonal_adjustment=True for `freq_table`
- updated doc string for both functions mentioned above

[Iss365] fix bug freq table seasonal adj

---

brightwind/analyse/analyse.py
brightwind/analyse/plot.py

added `bar_colors `inputs to `dist`,  `_bar_subplot`, `plot_freq_distribution`, `dist_of_wind_speed`

[Iss345] fix color dist of wind speed

---

brightwind/analyse/correlation.py
brightwind/analyse/plot.py

Iss268 add sector plot speed sort

---

CHANGELOG.md
brightwind/analyse/correlation.py
tests/test_correlation.py

Work in progress - doscstrings to be added as per Stephen's suggestion

iss412 fixed

---

brightwind/analyse/analyse.py

Issue #425 
I needed to redo the work as the feature branch had too many issues with it.
@ShaneBrightWind please review my small changes and if you are happy I will merge?
Thanks,

Iss425 time continuity docstring update

---

CHANGELOG.md
brightwind/load/load.py

Iss419 brighthub get data update url

---

CHANGELOG.md
brightwind/load/load.py

Issue #405 
Adding functionality to pull the cleaning log from BrightHub.

Iss405 brighthub cleaning log

---

CHANGELOG.md
brightwind/load/station.py

I have fixed the bug when calling is_file function in station.py. Note that I have looked if this issue was present anywhere else on all py files and I didn't find other issues.

[Iss447] fix isfile call

---

.github/workflows/tests.yml
brightwind/analyse/analyse.py
brightwind/analyse/plot.py
brightwind/analyse/shear.py
brightwind/load/station.py
brightwind/transform/transform.py
requirements.txt
setup.py
tests/test_correlation.py
tests/test_plot.py
tests/test_transform.py

Reverts brightwind-dev/brightwind#509

Revert "Update python, numpy, pandas"

---

.github/workflows/tests.yml

Closes #437 (?)
To be tested by enabling Github Actions back

Iss437 add env variables
