brightwind-dev/brightwind

- brightwind/analyse/correlation.py
- tests/test_correlation.py
> iss #308 fixed speed and direction coverage and added test

- brightwind/analyse/plot.py
- tests/test_plot.py
issue #224
fixed bug, now if x and y pandas series have same name then the correct scatter plot is generated
> Iss #224 plot scatter duplicate name

- CHANGELOG.md
- brightwind/analyse/analyse.py
- brightwind/analyse/correlation.py
- brightwind/transform/transform.py
- requirements.txt
- setup.py
- tests/test_analyse.py
- tests/test_correlation.py
- tests/test_shear.py
- tests/test_station.py
- tests/test_transform.py
Modifications to allow Brightwind library to be compatible with latest Pandas version (1+). The changes should allow the library to remain backward compatible with Pandas v0.24 as well.
Changes include:
- Panda v1+ has dropped support for 'M' and 'Y' in timeDelta function as the answer would vary depending on month and year. Instead this branch uses DateOffset to represent data frequency.
- All tests related to this change pass. There are some existing test conflict in the current dev branch unrelated to the new changes
- Some minor test conflicts are arising out of numerical floating point precision issues and there are minor fixes in the branch for those.
Suggestions:
- In future revision we should consider using pandas `infer_freq` to estimate data resolution. The current version is …
> Panda v1+ compatibility upgrdate. Minor test fixes

- brightwind/analyse/analyse.py
I think that python version used when having this error was Python 3.8.x, as I was able to replicate this issue ONLY when using Python 3.8.13. This error was raised with any `numpy version > 1.18.1` and `pandas==0.25.3`. This is probably due to a bug in ...\Anaconda3\envs\Python38\lib\site-packages\pandas\core\generic.py -> `describe` function
the `describe` function is taking as default input `include=None` but then np.numeric doesn't work. As for description below, for our application of describe function there is no need to give as input `include=None` but `include="All"` is ok and is not generating this error.
> [basic_stats] iss #307 fixed bug due to pandas version and python 3.8

- CHANGELOG.md
- brightwind/analyse/analyse.py
- brightwind/analyse/plot.py
Tests were performed from matplotlib==3.1.3 up to matplotlib==3.5.2 and confirmed that bug for ti_by_speed due to matplotlib version is fixed.
> Iss315 matplotlib version

- CHANGELOG.md
- brightwind/analyse/plot.py
- brightwind/analyse/shear.py
- brightwind/transform/transform.py
I did tests for different versions of numpy >= 1.20 and pandas >= 0.25.0 and errors below for #344 are solved. 
FAILED tests/test_correlation.py::test_synthesize - TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type
FAILED tests/test_correlation.py::test_speed_sort - TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type
FAILED tests/test_shear.py::test_time_of_day - AttributeError: type object 'object' has no attribute 'dtype'
FAILED tests/test_transform.py::test_merge_datasets_by_period - TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type
> Iss344 numpy version

- CHANGELOG.md
- brightwind/analyse/plot.py
- tests/test_plot.py
@stephenholleran  The following updates were made - more info are in #349 :
1. Added _timeseries_subplot function.
- this uses matplotlib.pyplot for plotting.
- this can be called several times for generating a figure with multiple subplots.
- It is taking the inputs below.
- _timeseries_subplot(x, y, x_label=None, y_label=None, x_limits=None, y_limits=None, x_tick_label_angle=0, line_marker_types=None, line_colors=COLOR_PALETTE.color_list, subplot_title=None, legend=True, ax=None)
1. Updates below for plot_timeseries function:
- use _timeseries_subplot instead of plotting functionality embedded within Pandas library
- as a consequence of above the tick labels of x_axis are formatted as for matplotlib.pyplot default tick labels format, see
- example plots below.
- as default the x_limits …
> [Iss349] Update plot timeseries

- CHANGELOG.md
- brightwind/export/export.py
- tests/test_export.py
Fix bug in `_calc_mean_speed_of_tab` which arises when the wind speed bin is less than 1 m/s. The bug involved undesired reordering of the frequency table index.
> [Iss359] Fix calculation of mean speed from frequency table

- brightwind/transform/transform.py
- tests/test_transform.py
- solved deprecation warning raised for Pandas v.1+ when `base` input is given to `pandas.resample` function 
- this was solved removing the `base` input as both pandas version < 1 and >1 are assuming this setting by default 
- I did a test for different resampling periods to check this
> [Iss325] solve resample warning

- brightwind/analyse/analyse.py
- brightwind/analyse/plot.py
As part of this issue I have:
1. Removed `plot_freq_distribution()` function from` dist()` and used `_bar_subplot` directly
2. Put a DeperactionWarning in `plot_freq_distribution `function
> [Iss335] deprecate plot freq distribution

- CHANGELOG.md
- brightwind/load/load.py
- requirements.txt
- setup.py
- tests/test_load.py
The following updates were made for `LoadBrightHub`:
1. Updated URL
2. Updated `_get_id_token` function to don't use `boto3`. This function was also updated to return specific errors depending on the response. 
3. Updated method to get id_token  only once
4. Added `_brighthub_refresh_token` function to return a new token if the current id_token has expired.  This function will return specific errors depending on the response
5. Added generic function `_brighthub_request` to make a GET request to the Brighthub endpoints
6. Updated the following functions to use the generic `_brighthub_request` above:  `get_plants`, `get_measurement_stations`, `get_start_end_dates`, `get_data_model`, `get_data`, `get_chunk`
7. Added tests
8. Updated Changelog
> [Iss355] updated brighthub url

- brightwind/analyse/plot.py
1. updated the `plot_scatter `, `plot_scatter_by_sector` to give as input to `_scatter_subplot` the scatter and trendline colors
2. updated `plot_timeseries` default `line_colors` input option
> [Iss310] different colours plot scatter

- CHANGELOG.md
- brightwind/analyse/correlation.py
- tests/test_correlation.py
The `SpeedSort.speed_model.sector_predict` function was updated to consider two fit lines:
1. line passing through zero and the cut off reference speed -> used for reference speeds < cut off
2. best fit line of points above cut off reference speed -> used for speeds >= cut off
> [Iss377] speedsort sector predict update

- brightwind/analyse/analyse.py
- tests/test_analyse.py
Fix iss382 regarding `_get_dist_matrix_by_dir_sector`. Error was thrown when `var_series` contained a month with zero coverage.
The solution is to only drop months which fail the coverage threshold if they have coverage greater than zero. If they have coverage equal to zero, then the month does not exist in the series.
Changed 
`var_series = tmp_var_series.set_index('Months').drop(labels=list( months_fail_coverage.index.strftime('%Y-%m'))).set_index(index_name).iloc[:, 0]`
To
`var_series = tmp_var_series.set_index('Months').drop(labels=list( months_fail_coverage[months_fail_coverage>0].index.strftime('%Y-%m'))).set_index(index_name).iloc[:, 0]`
> [Iss382] seas adj dist matrix

- CHANGELOG.md
- brightwind/analyse/analyse.py
- tests/test_analyse.py
1.  Added option to `momm` function to derive the seasonal adjusted mean of monthly mean speed if input `seasonal_adjustment` is True. 
2. added tests for `momm`
The seasonal adjusted mean of monthly mean is derived as for method below:
1) calculate monthly coverage
2) filter out any months with coverage lower than the input 'coverage_threshold'
3) derive the monthly mean for each calendar month (i.e. all January)
4) weighted average each monthly mean value based on the number of days in each month
(i.e. 31 days for January) - number of days for February are derived as average of actual days for the year
of the dataset. This to take into account leap years.
> [Iss298] momm seasonal adjusted

- brightwind/analyse/plot.py
A very small fix was made in `_bar_subplot` in order to handle minor update in matplotlib version=3.7.1  (not hadling nan or inf values for plot axis limits). This fix was tested with `matplotlib <= 3.7.1, Python <= 3.10.9, numpy <=1.24.1, pandas<=1.5.3` .
> [iss #389] fixed issue generating errors with matplotlib version=3.7.1

- brightwind/analyse/plot.py
- tests/test_plot.py
Solved bug for `plot_shear_by_sector` ignoring nan and inf values when defining the axis limits.
As part of this issue I have also added a docstring for  `plot_shear_by_sector` with examples and also tests for this function.
> [Iss397] plot shear by sector bug

- CHANGELOG.md
- brightwind/analyse/analyse.py
- brightwind/analyse/plot.py
- brightwind/load/load.py
- brightwind/transform/transform.py
- brightwind/utils/utils.py
- tests/test_analyse.py
- tests/test_load.py
- tests/test_plot.py
- tests/test_transform.py
- tests/test_utils.py
I have updated `slice_data`, `offset_timestamps`, `_LoadBWPlatform.get_data` functions to consider date_to input as not included. e.g if date_to = 2023-02-01 then sliced data, offsetted data and data we get from platform are considered up to 2023-01-31 23:50. This is consistent with method used for `bw.LoadBrightHub.get_data` and `load_cleaning_file`.
As part of this branch I have also:
1. updated the docstrings and tests of `slice_data`, `offset_timestamps`, `_LoadBWPlatform.get_data`. And also doctsrings of `momm`, `plot_timeseries` functions as using  `slice_data`.
2. fixed bugs below for `offset_timestamps`:
- In docstring it is stated that function can accept a datetime.time input but an error was raised when using this. This is fixed now.
- In docstring it is stated that the output …
> [Iss385] `slice_data`, `offset_timestamps`, `_LoadBWPlatform.get_data` date_to not included

- CHANGELOG.md
- brightwind/analyse/analyse.py
- tests/test_analyse.py
I have made the following updates to `freq_table`:
- make it use `_filter_out_months_based_on_coverage_threshold` function generated as part of #298. Warning messages for data coverage generated for `momm` and `freq_table` are now generated by same function and therefore similar.
- filter out both `var_series` and `direction_series` data when a coverage_threshold is given as input - this was a bug in previous version as coverage filter was based only on  `var_series` 
- added option of setting a `coverage_threshold` also for the basic method and not only for seasonal adjusted option. Similarly to `momm` (#298), I have updated the `coverage_threshold` default value to be None when no seasonal adj is applied and 0.8 with seas adj. This was done in order to avoid generating a breaking …
> [Iss386] freq table basic coverage thresh

- CHANGELOG.md
- brightwind/load/load.py
- brightwind/utils/utils.py
- requirements.txt
- setup.py
Solved error generated with pandas >= 2.0.0 for `slice_data` and `load_cleaning_file` due to update made in pandas for `pd.to_datetime()`. Pandas > 2.0.0 doesn't automatically recognise the format if a correct format or format =“ISO8601” or format=
“mixed” input is not given to `pd.to_datetime()`, as explained at link below. https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html#pandas.to_datetime
Tests were performed using following libraries and versions (and lower versions).
Python 3.11.3
brightwind 2.1.0.dev0
matplotlib 3.7.1
numpy 1.24.3
pandas 2.0.1
NOTE: This issue needs to be merged to `dev` after #385, otherwise merging conflicts and errors are raised for the tests.
> [Iss387] pandas version2 issues

- CHANGELOG.md
- brightwind/load/load.py
Previously, the cleaning function looks for a column in any part of the given column names, e.g. `Spd` would be found in `WSpd`. This has been updated to only clean out columns when the beginning of the name matches exactly that specified in the cleaning file.
Old operation:
Cleaning file `Spd` would clean out data from `WSpd` and `Spd` columns.
New operation:
Cleaning file `Spd` would clean out data from only the `Spd` column.
> [iss #249] clean based on column name matching from beginning of string

- CHANGELOG.md
- brightwind/__init__.py
- brightwind/analyse/plot.py
- setup.py
The `plot_shear_time_of_day` function in plot.py crashes **sometimes**. The real issue behind this fault is unclear - it looks to be a jupyter notebook issue. I think it's easier to update the `plot_shear_time_of_day` function to be more robust. The fix involves changing how the hour axis is is defined.
> [iss 429] bug fix for Shear.TimeOfDay

- CHANGELOG.md
- brightwind/analyse/plot.py
- tests/test_plot.py
The labels for 'data point' and '1:1 line' were mixed up for the `plot_scatter_wspds` and `plot_scatter_wdirs` now fixed.
> [Iss 443] Scatter plot label correction
